### ISSUE TITLE
Coloca em uma Hospedagem para vermos ao vivo o ReDesign

### ISSUE THREAD

**Issue by felipecastrosales** [eduardolecdt/onovomercado#1]
Isso faria com que fosse facilitada a exibição do mesmo, estou interessado em saber como ficou!

**Comment by eduardolecdt** [comment]
Está no ar em: https://eduardolecdt.github.io/onovomercado/

**Comment by felipecastrosales** [comment]
Caramba @eduardolecdt, que projeto foda! Ficou muito bom! Já pensou em mandar pra galera do suporte dele? Lança a braba! Tá lindo.
